---
apiVersion: "tekton.dev/v1beta1"
kind: "PipelineRun"
metadata:
  annotations:
    pipelinesascode.tekton.dev/on-event: "[create]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
  name: "git-demo-microservice"
spec:
  pipelineSpec:
    tasks:
      - name: fetch-source
        taskRef:
          resolver: cluster
          params:
            - name: repo
              value: demo-microservice
            - name: branch
              value: {{source_branch}}
