apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: custom-task
spec:
  steps:
    - name: build
      image: ghcr.io/gepaplexx/maven:$(params.maven-version)
      script: |-
        #!/usr/bin/env sh
        mvn -v
        echo $(params.repo)/$(params.branch)

  workspaces:
    - name: input
      description: Image with source code
      mountPath: /app
    - name: cache
      description: Cache for maven dependencies
      mountPath: /cache
    - name: sonar-cache
      description: Cache for sonarqube
      mountPath: /.sonar
  params:
    - name: repo
      type: string
    - name: branch
      type: string
    - name: sonar-host
      type: string
      default: http://cluster-sonarqube.gepaplexx-cicd-tools.svc.cluster.local
    - name: maven-version
      type: string
      default: latest


