---
apiVersion: "tekton.dev/v1beta1"
kind: "PipelineRun"
metadata:
  annotations:
    pipelinesascode.tekton.dev/task: "git-clone"
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[donnerstag*]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
  name: "git-demo-microservice"
spec:
  taskRunSpecs:
    - pipelineTaskName: fetch-source
      taskPodTemplate:
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          fsGroup: 65532
    - pipelineTaskName: maven-build
      taskPodTemplate:
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          fsGroup: 65532
    - pipelineTaskName: image-build # ...your git-clone PipelineTask name...
      taskServiceAccountName: pipelines-sa-userid-1000

  pipelineRef:
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: push-pipeline
      - name: namespace
        value: tekton-demo-microservice-cicd
  params:
    - name: repository-url
      value: {{repo_url}}
    - name: repository-name
      value: {{repo_name}}
    - name: repository-branch
      value: {{source_branch}}
    - name: maven-version
      value: 0.1.5
  workspaces:
    - name: code
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 300Mi
          volumeMode: Filesystem
    - name: maven-cache
      persistentVolumeClaim:
        claimName: maven-cache
    - name: sonar-cache
      persistentVolumeClaim:
        claimName: sonar-cache
    - name: ghcr-pat
      secret:
        secretName: ghcr-pat
    - name: trivy-cache
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          volumeMode: Filesystem
