---
apiVersion: "tekton.dev/v1beta1"
kind: "PipelineRun"
metadata:
  annotations:
    pipelinesascode.tekton.dev/task: "git-clone"
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
  name: "git-demo-microservice"
spec:
  taskRunSpecs:
  - pipelineTaskName: fetch-source # ...your git-clone PipelineTask name...
    taskPodTemplate:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
  - pipelineTaskName: maven-build # ...your git-clone PipelineTask name...
    taskPodTemplate:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
  - pipelineTaskName: image-build # ...your git-clone PipelineTask name...
    taskServiceAccountName: pipelines-sa-userid-1000

  pipelineSpec:
      workspaces:
        - name: code
      tasks:
        - name: fetch-source
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: code
          params:
            - name: url
              value: https://github.com/tomeindl/demo-microservice

        - name: maven-build
          runAfter:
            - fetch-source
          taskRef:
            resolver: cluster
            params:
              - name: kind
                value: task
              - name: name
                value: maven-build
              - name: namespace
                value: tekton-demo-microservice-cicd
          workspaces:
            - name: input
              workspace: code
            - name: cache
              workspace: maven-cache
            - name: sonar-cache
              workspace: sonar-cache
          params:
            - name: repo
              value: demo-microservice
            - name: branch
              value: main
            - name: userHome
              value: /home/git
        - name: image-build
          runAfter:
            - maven-build
          taskRef:
            resolver: cluster
            params:
              - name: kind
                value: task
              - name: name
                value: buildah-as-user
              - name: namespace
                value: tekton-demo-microservice-cicd
          workspaces:
            - name: code
              workspace: code
  workspaces:
    - name: code
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 300Mi
          volumeMode: Filesystem
    - name: maven-cache
      persistentVolumeClaim:
        claimName: maven-cache
    - name: sonar-cache
      persistentVolumeClaim:
        claimName: sonar-cache
