---
apiVersion: "tekton.dev/v1beta1"
kind: "PipelineRun"
metadata:
  annotations:
    pipelinesascode.tekton.dev/task: "git-clone"
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
  name: "git-demo-microservice"
spec:
  taskRunSpecs:
  - pipelineTaskName: fetch-source # ...your git-clone PipelineTask name...
    taskPodTemplate:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
  - pipelineTaskName: maven-build
    taskPodTemplate:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
  - pipelineTaskName: image-build
    taskServiceAccountName: pipelines-sa-userid-1000

  pipelineSpec:
      workspaces:
        - name: code
      tasks:
        #Tekton Hub task, needs to be referenced in the annotations
        - name: fetch-source
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: code
          params:
            - name: url
              value: {{repo_url}}
        #Task on the cluster, needs the cluster resolver
        - name: maven-build
          runAfter:
            - fetch-source
          taskRef:
            resolver: cluster
            params:
              - name: kind
                value: task
              - name: name
                value: maven-build
              - name: namespace
                value: tekton-demo-microservice-cicd
          workspaces:
            - name: input
              workspace: code
            - name: cache
              workspace: maven-cache
            - name: sonar-cache
              workspace: sonar-cache
          params:
            - name: repo
              value: {{repo_name}}
            - name: branch
              value: {{source_branch}}
            - name: maven-version
              value: 0.1.5
        #Task on the cluster, needs the cluster resolver
        - name: image-build
          runAfter:
            - maven-build
          taskRef:
            resolver: cluster
            params:
              - name: kind
                value: task
              - name: name
                value: buildah-as-user
              - name: namespace
                value: tekton-demo-microservice-cicd
          workspaces:
            - name: code
              workspace: code
            - name: ghcr-pat
              workspace: ghcr-pat
        - name: image-scan
          runAfter:
            - image-build
          taskRef:
            resolver: cluster
            params:
              - name: kind
                value: task
              - name: name
                value: scan-image-trivy
              - name: namespace
                value: tekton-demo-microservice-cicd
          workspaces:
            - name: workspace
              workspace: code
            - name: ghcr-pat
              workspace: ghcr-pat
            - name: cache
              workspace: trivy-cache

  workspaces:
    # the working directory where code is checked out into
    - name: code
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 300Mi
          volumeMode: Filesystem
    # caches, built with helm on cluster, just referenced
    - name: maven-cache
      persistentVolumeClaim:
        claimName: maven-cache
    - name: sonar-cache
      persistentVolumeClaim:
        claimName: sonar-cache
    # secret mounted into pod
    - name: ghcr-pat
      secret:
        secretName: ghcr-pat
    # cache for trivy image scan
    - name: trivy-cache
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          volumeMode: Filesystem
