---
apiVersion: "tekton.dev/v1beta1"
kind: "PipelineRun"
metadata:
  annotations:
    pipelinesascode.tekton.dev/task: "[git-clone, maven-build]"
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
  name: "git-demo-microservice"
spec:
  pipelineSpec:
      workspaces:
        - name: code
      tasks:
        - name: fetch-source
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: code
          params:
            - name: url
              value: https://github.com/sgartner03/demo-microservice
            - name: subdirectory
              value: /app
        - name: maven-build
          runAfter:
            - fetch-source
          taskRef:
            name: maven-build
          workspaces:
            - name: input
              workspace: code
